# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
  - main

pool:
  vmImage: 'macos-latest'

steps:
  - task: UseFlutterVersion@0
    inputs:
    version: 'stable'

  - script: flutter pub get
    displayName: 'Install dependencies'

  - script: flutter test
    displayName: 'Run unit tests'

  - script: flutter build apk --release
    displayName: 'Build Release APK'