# Azure DevOps Pipeline for Android (Flutter)
# Docs: https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
  - main

pool:
  vmImage: "macos-latest"

steps:
  - script: git clone https://github.com/flutter/flutter.git -b 3.35.0 --depth 1
    displayName: "Clone Flutter SDK (3.35.0)"

  - script: echo "##vso[task.prependpath]$(pwd)/flutter/bin"
    displayName: "Add Flutter to PATH"

  - script: flutter --version
    displayName: "Check Flutter Version"

  - script: flutter pub get
    displayName: "Install dependencies"

  - script: flutter test
    displayName: "Run unit tests"

  - script: flutter build apk --release
    displayName: "Build Release APK"