# Azure DevOps Pipeline for Android (Flutter)
# Docs: https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
  - main

pool:
  vmImage: "macos-latest"

steps:
  - task: UseFlutterVersion@3.35
    inputs:
      version: "stable"

  - script: flutter pub get
    displayName: "Install dependencies"

  - script: flutter test
    displayName: "Run unit tests"

  - script: flutter build apk --release
    displayName: "Build Release APK"
