# Azure DevOps Pipeline for Android (Flutter)
# Docs: https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
  - main

pool:
  vmImage: "macos-latest"

steps:
  - script: |
      git clone https://github.com/flutter/flutter.git -b stable --depth 1
      echo "##vso[task.prependpath]$(pwd)/flutter/bin"
      flutter --version
    displayName: "Install Flutter SDK"
  - script: |
      git clone https://github.com/flutter/flutter.git -b 3.35.0 --depth 1
      echo "##vso[task.prependpath]$(pwd)/flutter/bin"
      flutter --version
    displayName: "Install Flutter SDK (3.13.5)"

  - script: flutter pub get
    displayName: "Install dependencies"

  - script: flutter test
    displayName: "Run unit tests"

  - script: flutter build apk --release
    displayName: "Build Release APK"