# Azure DevOps Pipeline for Android (Flutter)
# Docs: https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
  - main

pool:
  vmImage: "macos-latest"

steps:
  - script: |
      git clone https://github.com/flutter/flutter.git -b stable --depth 1
      echo "##vso[task.prependpath]$(pwd)/flutter/bin"
      flutter --version
    displayName: "Install Flutter SDK"

  - script: |
      export PATH="$PATH:$(pwd)/flutter/bin"
      flutter pub get
    displayName: "Install dependencies"

  - script: |
      export PATH="$PATH:$(pwd)/flutter/bin"
      flutter test
    displayName: "Run unit tests"

  - script: |
      export PATH="$PATH:$(pwd)/flutter/bin"
      flutter build apk --release
    displayName: "Build Release APK"