# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
  - main

pool:
  vmImage: 'macos-latest'

steps:
  # Install Flutter
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        git clone https://github.com/flutter/flutter.git -b stable --depth 1
        export PATH="$PATH:`pwd`/flutter/bin"
        flutter doctor

  # Get dependencies
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        export PATH="$PATH:`pwd`/flutter/bin"
        flutter pub get

  # Build Android APK using Gradle
  - task: Gradle@2
    inputs:
      workingDirectory: 'android'
      gradleWrapperFile: 'android/gradlew'
      gradleOptions: '-Xmx3072m'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'assembleDebug'
