// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqeG4tfU1Tcyysp_EGgGHVA216qvNG9Yg',
    appId: '1:1023162809872:web:93fa5a2086f4aeb0881495',
    messagingSenderId: '1023162809872',
    projectId: 'gosalamina-b581d',
    authDomain: 'gosalamina-b581d.firebaseapp.com',
    storageBucket: 'gosalamina-b581d.firebasestorage.app',
    measurementId: 'G-45RSXD2RSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY0pCOWr1-zz0uX6gL52buqBkgAsI8LY0',
    appId: '1:1023162809872:android:1e61a9c498a19178881495',
    messagingSenderId: '1023162809872',
    projectId: 'gosalamina-b581d',
    storageBucket: 'gosalamina-b581d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb9DuBtWgW6b4AsBbhbTsCVdFdVYFMft4',
    appId: '1:1023162809872:ios:b8345d122846d345881495',
    messagingSenderId: '1023162809872',
    projectId: 'gosalamina-b581d',
    storageBucket: 'gosalamina-b581d.firebasestorage.app',
    iosBundleId: 'com.goventures.user',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb9DuBtWgW6b4AsBbhbTsCVdFdVYFMft4',
    appId: '1:1023162809872:ios:b8345d122846d345881495',
    messagingSenderId: '1023162809872',
    projectId: 'gosalamina-b581d',
    storageBucket: 'gosalamina-b581d.firebasestorage.app',
    iosBundleId: 'com.goventures.user',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqeG4tfU1Tcyysp_EGgGHVA216qvNG9Yg',
    appId: '1:1023162809872:web:5fac4d5c7ac3ad88881495',
    messagingSenderId: '1023162809872',
    projectId: 'gosalamina-b581d',
    authDomain: 'gosalamina-b581d.firebaseapp.com',
    storageBucket: 'gosalamina-b581d.firebasestorage.app',
    measurementId: 'G-0B7TT317M7',
  );

}