// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY0pCOWr1-zz0uX6gL52buqBkgAsI8LY0',
    appId: '1:1023162809872:android:68f449b4f017f0ad881495',
    messagingSenderId: '1023162809872',
    projectId: 'gosalamina-b581d',
    storageBucket: 'gosalamina-b581d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb9DuBtWgW6b4AsBbhbTsCVdFdVYFMft4',
    appId: '1:1023162809872:ios:0050a77e4afcb33a881495',
    messagingSenderId: '1023162809872',
    projectId: 'gosalamina-b581d',
    storageBucket: 'gosalamina-b581d.firebasestorage.app',
    iosBundleId: 'com.goventures.app',
  );
}
